services:
  gateway-api:
    image: codechallenge-sg/gateway-api
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - proxybackend
    environment:
      - JWT__Key=TiFBblSqOR1EAvuW4hojfyxoTB9T0VH4HvgHTNurKBYlEYX2pUMbv62R3zA7Qv6vfBGiEEIylqghEWqz5WMzp7DEhohyRv7i25SvOis2ABwxg6Mlf8rtwoQW6VDaYFDP
      - ASPNETCORE_ENVIRONMENT=Development

  cuenta-service:
    image: codechallenge-sg/cuenta-service
    build:
      context: ./Services/CuentaService
      dockerfile: Dockerfile
    networks:
      - proxybackend
      - dbnetwork1
    environment:
      JWT__Key: "TiFBblSqOR1EAvuW4hojfyxoTB9T0VH4HvgHTNurKBYlEYX2pUMbv62R3zA7Qv6vfBGiEEIylqghEWqz5WMzp7DEhohyRv7i25SvOis2ABwxg6Mlf8rtwoQW6VDaYFDP"
      ConnectionStrings__SG: "Server=sgdb,1433;Database=SG;User Id=sa;Password=password@12345#;Encrypt=false;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: "Development"

  auth-service:
    image: codechallenge-sg/auth-service
    build:
      context: ./Services/AuthService
      dockerfile: Dockerfile
    networks:
      - proxybackend
      - dbnetwork1
    environment:
      JWT__Key: "TiFBblSqOR1EAvuW4hojfyxoTB9T0VH4HvgHTNurKBYlEYX2pUMbv62R3zA7Qv6vfBGiEEIylqghEWqz5WMzp7DEhohyRv7i25SvOis2ABwxg6Mlf8rtwoQW6VDaYFDP"
      ConnectionStrings__SG: "Server=sgdb,1433;Database=SG;User Id=sa;Password=password@12345#;Encrypt=false;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: "Development"

  sgdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password@12345#
    ports:
      - 11433:1433
    networks:
      - dbnetwork1
    volumes:
    - "./mssql/data/:/var/opt/mssql/data/"
    - "./mssql/log/:/var/opt/mssql/log/"
    - "./mssql/secrets/:/var/opt/mssql/secrets/"

networks:
  proxybackend:
    name: proxybackend
    driver: bridge
  dbnetwork1:
    name: dbnetwork1
    driver: bridge
